# Generated by Django 4.2.2 on 2023-12-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='User_Answer',
        ),
    ]
