# Generated by Django 4.2.2 on 2023-12-08 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_answer_user_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_answer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question'),
        ),
    ]
