# Generated by Django 4.2.2 on 2023-12-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_answer_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_answer',
            old_name='questions',
            new_name='questions_id',
        ),
    ]
