# Generated by Django 4.2.2 on 2023-12-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_questions_user_answer_questions_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answer',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quiz'),
        ),
    ]
