# Generated by Django 4.2.2 on 2023-12-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
