# Generated by Django 4.2.2 on 2023-12-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_answer',
            old_name='complet',
            new_name='completed',
        ),
    ]
