# Generated by Django 4.2.2 on 2023-12-15 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_complet_user_answer_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Answer',
            new_name='UserAnswer',
        ),
    ]
