# Generated by Django 4.2.2 on 2023-12-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_user_answer_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
