# Generated by Django 4.2.2 on 2023-12-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_question_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
    ]
